updated gkrellm recipe for packaging conformance

diff --git a/recipes-extended/gkrellm/gkrellm/gkrellmd b/recipes-extended/gkrellm/gkrellm/gkrellmd
--- a/recipes-extended/gkrellm/gkrellm/gkrellmd
+++ b/recipes-extended/gkrellm/gkrellm/gkrellmd
@@ -1,22 +1,40 @@
 #!/bin/sh
-#
+### BEGIN INIT INFO
+# Provides:          gkrellmd
+# Required-Start:    $remote_fs
+# Required-Stop:     $remote_fs
+# Default-Start:     2 3 4 5
+# Default-Stop:      0 1 6
+# Short-Description: System monitoring daemon
+### END INIT INFO
 
-APP_PATH="/usr/sbin"
-MONITOR_APP="gkrellmd"
+PATH=/bin:/usr/bin:/sbin:/usr/sbin
 
 case "$1" in
-
-  start)
-    $APP_PATH/$MONITOR_APP > /dev/null 2>&1
-    ;;
-
-  stop)
-    killall $MONITOR_APP
-    ;;
-
-  restart)
-    killall $MONITOR_APP
-    sleep 3
-    $APP_PATH/$MONITOR_APP > /dev/null 2>&1
-    ;;
+    start)
+	echo -n "Starting system monitoring daemon: "
+	start-stop-daemon -S -x /usr/sbin/gkrellmd
+	if [ $? = 0 ]; then
+	    echo "gkrellmd."
+	else
+	    echo "(failed.)"
+	fi
+	;;
+    stop)
+	echo -n "Stopping system monitoring daemon: "
+	start-stop-daemon -K \
+		-x /usr/sbin/gkrellmd
+	echo "gkrellmd."
+	;;
+    restart|force-reload) 
+	$0 stop
+	$0 start
+	exit
+	;;
+    *)
+	echo "Usage: /etc/init.d/gkrellmd {start|stop|restart|force-reload}"
+	exit 1
+	;;
 esac
+
+exit 0
